version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.9.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "yarn.lock" }}
      - run:
          name: dependency-install
          command: yarn install --dev
      - save_cache:
          key: dep-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - .node_modules
  test:
    docker:
      - image: circleci/node:7.9.0-browsers
    steps:
      - checkout
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: 'yarn test'
      # - run:
      #     name: code-coverage
      #     command: 'yarn test'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build