export const ERROR_PARAM_REQUIRED = 'ERROR_PARAM_REQUIRED';

export const MESSAGE_SET_CREDENTIALS = 'MESSAGE_SET_CREDENTIALS';
export const MESSAGE_CREDENTIALS_SET = 'MESSAGE_CREDENTIALS_SET';
export const MESSAGE_DELETE_CREDENTIALS = 'MESSAGE_DELETE_CREDENTIALS';
export const MESSAGE_CREDENTIALS_DELETED = 'MESSAGE_CREDENTIALS_DELETED';
